### PR TITLE
crashed event warning

### LINKED ISSUE #67: "Listen for crash events" warning showing, not correct?
Hey! Devtron is awesome, but it's giving this warning in the Lint panel:

image

However, we do have a listener attached https://github.com/nylas/N1/blob/master/src/browser/nylas-window.coffee#L198, and I can verify that it's working properly by force-emitting a crashed event from the dev tools console within the window:

`remote.getCurrentWebContents().emit('crashed')`

Maybe it's not picking it up because the listener is in the main process and not within the renderer process?

### PR DESCRIPTION
**Pull request by princejwesley**
[This commit](https://github.com/electron/electron/commit/76853801051be1dfbe94cb855567b5c901f9f12d) removed crashed event forwarding for tags `1.x.y`
image
Fixes #67

### CODE REVIEW

File: lib/lint-helpers.js [hunk 1]
```diff
@@ -11,9 +11,13 @@ exports.isUsingAsar = () => {
...
 exports.isListeningForCrashEvents = () => {
   return Eval.execute(() => {
-    const webContents = require('electron').remote.getCurrentWebContents()
-    // Electron has a crashed listener, so look for more than 1
-    return webContents.listenerCount('crashed') > 1
+    const remote = require('electron').remote
+    const webContents = remote.getCurrentWebContents()
+    // For versions less than 1.x.y
+    // Electron has an crashed listener, so look for more than 1
+    const crashedForwarding = /^0/.test(remote.process.versions.electron)
```
Comment (kevinsawicki) [inline lib/lint-helpers.js]: You don't need the `remote.` here, `process.versions.electron` is available directly in the renderer process.

**Comment by kevinsawicki** [comment]
Thanks for this 👍
